// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function helloWorld(param) {
  console.log("Hello world");
  return /* () */0;
}

console.log("Hello world");

exports.helloWorld = helloWorld;
/*  Not a pure module */
